// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gffhkotvbwcsvchfieoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZmhrb3R2Yndjc3ZjaGZpZW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzI1MzIsImV4cCI6MjA2ODgwODUzMn0.XcF5BWLoJ7JfvvgEfvldpXjN_IrdmxM2JyfXuic7Z3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});